language: python
python:
  - "2.7"
env:
  - DJANGO=1.5.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
before_script:

script:
  - python setup.py test
